# Generated by Django 3.0.6 on 2020-05-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stumee_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image_url',
            new_name='user_image',
        ),
    ]
