# Generated by Django 3.0.5 on 2020-04-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumee_meeting', '0002_commentgood'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
    ]
