# Generated by Django 3.0.5 on 2020-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumee_meeting', '0003_comment_good_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='stumee_meeting',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
    ]
