# Generated by Django 3.0.5 on 2020-04-22 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumee_meeting', '0004_thread_good_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='up_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='stumee_meeting',
            name='make_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
