# Generated by Django 3.0.5 on 2020-05-06 05:53

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('stumee_meeting', '0005_auto_20200422_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
